// GET all users
GET http://localhost:3600/users
Accept: application/json
Authorization: {{bearer}}

###
// Create new user
POST http://localhost:3600/users
Content-Type: application/json

{
  "firstName" : "paidUser",
  "lastName" : "paidUser",
  "email" : "paid.paid@gmail.com",
  "password" : "123"
}

###
// PATCH existing user
PATCH http://localhost:3600/users/6380e91fba67b23b786d8af6
Content-Type: application/json
Authorization: {{bearer}}

{
  "firstName" : "teeee",
  "lastName" : "Silva",
  "email" : "marcos.henrique@toptal.com",
  "password" : "s3cr3tp4sswo4rd"
}

###
// GET specific user
GET http://localhost:3600/users/6380e91fba67b23b786d8af6
Accept: application/json
Authorization: {{bearer}}

###
// DELETE specific user
DELETE http://localhost:3600/users/637d18e381dacb47dc4ef5cc
Accept: application/json
Authorization: {{bearer}}

###
// POST authentication
POST http://localhost:3600/auth
Content-Type: application/json

{
  "email" : "gostner.emanuel@gmail.com",
  "password" : "123"
}

###
// POST authentication
POST http://localhost:3600/auth
Content-Type: application/json

{
  "email" : "paid.paid@gmail.com",
  "password" : "123"
}

###

